name: orders testing
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TIME_ZONE: ${{ vars.TIME_ZONE }}
      DEBUG: ${{ vars.DEBUG }}
      ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ vars.DB_ENGINE }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      WORKING-DIRECTORY: orders/
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверка репозитория на наличие обновлений
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установка зависимостей Python
        run: pip install -r requirements-test.txt

      - name: Линтинг
        run: flake8 orders --max-complexity=10 --max-line-length=120 --ignore=F403,F405 --exclude=migrations --count
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Тестирование
        run: |
          python3 manage.py migrate
          pytest tests --cov=backend
        working-directory: ${{env.WORKING-DIRECTORY}}
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          PAGINATION_PAGE_SIZE: 100
          THROTTLE_RATE_ANON_PERMINUTE: 100000
          THROTTLE_RATE_USER_PERMINUTE: 100000
